# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MGViYThmODY3YzhlNDM1ZDNmOTU0OTA4YjU3ZjIwZDQ4MDA5ZGNlZDRmYmViYTQ5NTNjZmZhNmQ2YTI0YmQ3Mjk3OGFkNzJhMzdmYmM5MTM0YzVjZjZkNGMyYTM3YmFjYmRkMzk3MWQ1NTMzOTY5MTUwZGY4NDhlOGQ5MTgyNDI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
